name: stamp_logo_on_image
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.1.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.4.10
  path_provider: ^0.4.1
  path: any
  #IMPORTANT! for iOS change the dependency to that package
  #image_picker_saver: ^0.1.0
  uuid: ^1.0.3
  simple_permissions: ^0.1.8
  image: ^2.0.4
  photo_view: ^0.0.10
  fluttertoast: ^2.2.3
  image_picker_saver:
    path: ../image_picker_saver
  flutter_share_content: ^0.1.0
  flutter_exif_rotation: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: "Example-Icon"
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
